spring:
  application:
    # 이 이름은 Eureka 서버의 이름을 정의하며, 다른 서비스들이 이 이름을 통해 Eureka 서버를 찾을 수 있습니다.
    name: eureka-server


server:
  # Eureka 서버가 실행될 포트 번호 설정하는 곳인데 기본적은 8761 포트에서 실행됩니다.
  # 다른 서비스들이 이 포트를 통해 Eureka 서버와 통신하게 됩니다.
  port: 8761

eureka:
  client:
    # Eureka 서버는 자기 자신을 Eureka 서버 목록에 등록하지 않도록 설정
    # 'false'로 설정하면 Eureka 서버는 다른 서비스들이 자신을 등록할 수 있도록 하되,
    # 자기 자신을 등록하지 않습니다. Eureka 서버는 클라이언트 서비스를 등록받는 역할만 합니다.
    register-with-eureka: false
    
    # Eureka 서버는 다른 Eureka 서버에서 서비스 목록을 가져오지 않도록 설정
    # 'false'로 설정하면, 이 서버는 다른 Eureka 서버에서 레지스트리(서비스 목록)를 가져오지 않으며
    # 단일 Eureka 서버 환경에서 동작하게 됩니다.
    fetch-registry: false
